/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export type GetScoresResponseData =
  | AntsPlatformAPI.GetScoresResponseData.Numeric
  | AntsPlatformAPI.GetScoresResponseData.Categorical
  | AntsPlatformAPI.GetScoresResponseData.Boolean;

export namespace GetScoresResponseData {
  export interface Numeric
    extends AntsPlatformAPI.GetScoresResponseDataNumeric {
    dataType: "NUMERIC";
  }

  export interface Categorical
    extends AntsPlatformAPI.GetScoresResponseDataCategorical {
    dataType: "CATEGORICAL";
  }

  export interface Boolean
    extends AntsPlatformAPI.GetScoresResponseDataBoolean {
    dataType: "BOOLEAN";
  }
}
