/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface Traces {
  data: AntsPlatformAPI.TraceWithDetails[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
