/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface PaginatedSessions {
  data: AntsPlatformAPI.Session[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
