/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetAnnotationQueueItemsRequest {
  /**
   * Filter by status
   */
  status?: AntsPlatformAPI.AnnotationQueueStatus;
  /**
   * page number, starts at 1
   */
  page?: number;
  /**
   * limit of items per page
   */
  limit?: number;
}
