/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface AnnotationQueueItem {
  id: string;
  queueId: string;
  objectId: string;
  objectType: AntsPlatformAPI.AnnotationQueueObjectType;
  status: AntsPlatformAPI.AnnotationQueueStatus;
  completedAt?: string;
  createdAt: string;
  updatedAt: string;
}
