/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface CreateAnnotationQueueItemRequest {
  objectId: string;
  objectType: AntsPlatformAPI.AnnotationQueueObjectType;
  /** Defaults to PENDING for new queue items */
  status?: AntsPlatformAPI.AnnotationQueueStatus;
}
