/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface PaginatedAnnotationQueues {
  data: AntsPlatformAPI.AnnotationQueue[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
