/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface PaginatedDatasetRunItems {
  data: AntsPlatformAPI.DatasetRunItem[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
