/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface ResourceType {
  schemas?: string[];
  id: string;
  name: string;
  endpoint: string;
  description: string;
  schema: string;
  schemaExtensions: AntsPlatformAPI.SchemaExtension[];
  meta: AntsPlatformAPI.ResourceMeta;
}
