/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface ScimUser {
  schemas: string[];
  id: string;
  userName: string;
  name: AntsPlatformAPI.ScimName;
  emails: AntsPlatformAPI.ScimEmail[];
  meta: AntsPlatformAPI.UserMeta;
}
