/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface ServiceProviderConfig {
  schemas: string[];
  documentationUri: string;
  patch: AntsPlatformAPI.ScimFeatureSupport;
  bulk: AntsPlatformAPI.BulkConfig;
  filter: AntsPlatformAPI.FilterConfig;
  changePassword: AntsPlatformAPI.ScimFeatureSupport;
  sort: AntsPlatformAPI.ScimFeatureSupport;
  etag: AntsPlatformAPI.ScimFeatureSupport;
  authenticationSchemes: AntsPlatformAPI.AuthenticationScheme[];
  meta: AntsPlatformAPI.ResourceMeta;
}
