/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface ScoreConfigs {
  data: AntsPlatformAPI.ScoreConfig[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
