/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface PaginatedModels {
  data: AntsPlatformAPI.Model[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
