/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface Comment {
  id: string;
  projectId: string;
  createdAt: string;
  updatedAt: string;
  objectType: AntsPlatformAPI.CommentObjectType;
  objectId: string;
  content: string;
  authorUserId?: string;
}
