/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface NumericScore extends AntsPlatformAPI.BaseScore {
  /** The numeric value of the score */
  value: number;
}
