/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export type Score =
  /**
   * Score with NUMERIC data type */
  | AntsPlatformAPI.Score.Numeric
  /**
   * Score with CATEGORICAL data type */
  | AntsPlatformAPI.Score.Categorical
  /**
   * Score with BOOLEAN data type */
  | AntsPlatformAPI.Score.Boolean;

export namespace Score {
  export interface Numeric extends AntsPlatformAPI.NumericScore {
    dataType: "NUMERIC";
  }

  export interface Categorical extends AntsPlatformAPI.CategoricalScore {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends AntsPlatformAPI.BooleanScore {
    dataType: "BOOLEAN";
  }
}
