/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export type ScoreV1 =
  /**
   * Score with NUMERIC data type */
  | AntsPlatformAPI.ScoreV1.Numeric
  /**
   * Score with CATEGORICAL data type */
  | AntsPlatformAPI.ScoreV1.Categorical
  /**
   * Score with BOOLEAN data type */
  | AntsPlatformAPI.ScoreV1.Boolean;

export namespace ScoreV1 {
  export interface Numeric extends AntsPlatformAPI.NumericScoreV1 {
    dataType: "NUMERIC";
  }

  export interface Categorical extends AntsPlatformAPI.CategoricalScoreV1 {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends AntsPlatformAPI.BooleanScoreV1 {
    dataType: "BOOLEAN";
  }
}
