/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface SessionWithTraces extends AntsPlatformAPI.Session {
  traces: AntsPlatformAPI.Trace[];
}
