/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface TraceWithDetails extends AntsPlatformAPI.Trace {
  /** Path of trace in AntsPlatform UI */
  htmlPath: string;
  /** Latency of trace in seconds */
  latency: number;
  /** Cost of trace in USD */
  totalCost: number;
  /** List of observation ids */
  observations: string[];
  /** List of score ids */
  scores: string[];
}
