/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

/**
 * List of API keys for a project
 */
export interface ApiKeyList {
  apiKeys: AntsPlatformAPI.ApiKeySummary[];
}
