/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export type ChatMessageWithPlaceholders =
  | AntsPlatformAPI.ChatMessageWithPlaceholders.Chatmessage
  | AntsPlatformAPI.ChatMessageWithPlaceholders.Placeholder;

export namespace ChatMessageWithPlaceholders {
  export interface Chatmessage extends AntsPlatformAPI.ChatMessage {
    type: "chatmessage";
  }

  export interface Placeholder extends AntsPlatformAPI.PlaceholderMessage {
    type: "placeholder";
  }
}
