/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export type CreatePromptRequest =
  | AntsPlatformAPI.CreatePromptRequest.Chat
  | AntsPlatformAPI.CreatePromptRequest.Text;

export namespace CreatePromptRequest {
  export interface Chat extends AntsPlatformAPI.CreateChatPromptRequest {
    type: "chat";
  }

  export interface Text extends AntsPlatformAPI.CreateTextPromptRequest {
    type: "text";
  }
}
