/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface PromptMetaListResponse {
  data: AntsPlatformAPI.PromptMeta[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
