/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export type Prompt = AntsPlatformAPI.Prompt.Chat | AntsPlatformAPI.Prompt.Text;

export namespace Prompt {
  export interface Chat extends AntsPlatformAPI.ChatPrompt {
    type: "chat";
  }

  export interface Text extends AntsPlatformAPI.TextPrompt {
    type: "text";
  }
}
