/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core/index.js";
import * as AntsPlatformAPI from "../../../index.js";
import {
  mergeHeaders,
  mergeOnlyDefinedHeaders,
} from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace AnnotationQueues {
  export interface Options {
    environment: core.Supplier<string>;
    /** Specify a custom URL to connect the client to. */
    baseUrl?: core.Supplier<string>;
    username?: core.Supplier<string | undefined>;
    password?: core.Supplier<string | undefined>;
    /** Override the X-AntsPlatform-Sdk-Name header */
    xAntsPlatformSdkName?: core.Supplier<string | undefined>;
    /** Override the X-AntsPlatform-Sdk-Version header */
    xAntsPlatformSdkVersion?: core.Supplier<string | undefined>;
    /** Override the X-AntsPlatform-Public-Key header */
    xAntsPlatformPublicKey?: core.Supplier<string | undefined>;
    /** Additional headers to include in requests. */
    headers?: Record<
      string,
      string | core.Supplier<string | undefined> | undefined
    >;
  }

  export interface RequestOptions {
    /** The maximum time to wait for a response in seconds. */
    timeoutInSeconds?: number;
    /** The number of times to retry the request. Defaults to 2. */
    maxRetries?: number;
    /** A hook to abort the request. */
    abortSignal?: AbortSignal;
    /** Override the X-AntsPlatform-Sdk-Name header */
    xAntsPlatformSdkName?: string | undefined;
    /** Override the X-AntsPlatform-Sdk-Version header */
    xAntsPlatformSdkVersion?: string | undefined;
    /** Override the X-AntsPlatform-Public-Key header */
    xAntsPlatformPublicKey?: string | undefined;
    /** Additional query string parameters to include in the request. */
    queryParams?: Record<string, unknown>;
    /** Additional headers to include in the request. */
    headers?: Record<
      string,
      string | core.Supplier<string | undefined> | undefined
    >;
  }
}

export class AnnotationQueues {
  protected readonly _options: AnnotationQueues.Options;

  constructor(_options: AnnotationQueues.Options) {
    this._options = _options;
  }

  /**
   * Get all annotation queues
   *
   * @param {AntsPlatformAPI.GetAnnotationQueuesRequest} request
   * @param {AnnotationQueues.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AntsPlatformAPI.Error}
   * @throws {@link AntsPlatformAPI.UnauthorizedError}
   * @throws {@link AntsPlatformAPI.AccessDeniedError}
   * @throws {@link AntsPlatformAPI.MethodNotAllowedError}
   * @throws {@link AntsPlatformAPI.NotFoundError}
   *
   * @example
   *     await client.annotationQueues.listQueues()
   */
  public listQueues(
    request: AntsPlatformAPI.GetAnnotationQueuesRequest = {},
    requestOptions?: AnnotationQueues.RequestOptions,
  ): core.HttpResponsePromise<AntsPlatformAPI.PaginatedAnnotationQueues> {
    return core.HttpResponsePromise.fromPromise(
      this.__listQueues(request, requestOptions),
    );
  }

  private async __listQueues(
    request: AntsPlatformAPI.GetAnnotationQueuesRequest = {},
    requestOptions?: AnnotationQueues.RequestOptions,
  ): Promise<core.WithRawResponse<AntsPlatformAPI.PaginatedAnnotationQueues>> {
    const { page, limit } = request;
    const _queryParams: Record<
      string,
      string | string[] | object | object[] | null
    > = {};
    if (page != null) {
      _queryParams["page"] = page.toString();
    }

    if (limit != null) {
      _queryParams["limit"] = limit.toString();
    }

    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/annotation-queues",
      ),
      method: "GET",
      headers: mergeHeaders(
        this._options?.headers,
        mergeOnlyDefinedHeaders({
          Authorization: await this._getAuthorizationHeader(),
          "X-AntsPlatform-Sdk-Name": requestOptions?.xAntsPlatformSdkName,
          "X-AntsPlatform-Sdk-Version": requestOptions?.xAntsPlatformSdkVersion,
          "X-AntsPlatform-Public-Key": requestOptions?.xAntsPlatformPublicKey,
        }),
        requestOptions?.headers,
      ),
      queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as AntsPlatformAPI.PaginatedAnnotationQueues,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AntsPlatformAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new AntsPlatformAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new AntsPlatformAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new AntsPlatformAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new AntsPlatformAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.AntsPlatformAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.AntsPlatformAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.AntsPlatformAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/annotation-queues.",
        );
      case "unknown":
        throw new errors.AntsPlatformAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get an annotation queue by ID
   *
   * @param {string} queueId - The unique identifier of the annotation queue
   * @param {AnnotationQueues.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AntsPlatformAPI.Error}
   * @throws {@link AntsPlatformAPI.UnauthorizedError}
   * @throws {@link AntsPlatformAPI.AccessDeniedError}
   * @throws {@link AntsPlatformAPI.MethodNotAllowedError}
   * @throws {@link AntsPlatformAPI.NotFoundError}
   *
   * @example
   *     await client.annotationQueues.getQueue("queueId")
   */
  public getQueue(
    queueId: string,
    requestOptions?: AnnotationQueues.RequestOptions,
  ): core.HttpResponsePromise<AntsPlatformAPI.AnnotationQueue> {
    return core.HttpResponsePromise.fromPromise(
      this.__getQueue(queueId, requestOptions),
    );
  }

  private async __getQueue(
    queueId: string,
    requestOptions?: AnnotationQueues.RequestOptions,
  ): Promise<core.WithRawResponse<AntsPlatformAPI.AnnotationQueue>> {
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/annotation-queues/${encodeURIComponent(queueId)}`,
      ),
      method: "GET",
      headers: mergeHeaders(
        this._options?.headers,
        mergeOnlyDefinedHeaders({
          Authorization: await this._getAuthorizationHeader(),
          "X-AntsPlatform-Sdk-Name": requestOptions?.xAntsPlatformSdkName,
          "X-AntsPlatform-Sdk-Version": requestOptions?.xAntsPlatformSdkVersion,
          "X-AntsPlatform-Public-Key": requestOptions?.xAntsPlatformPublicKey,
        }),
        requestOptions?.headers,
      ),
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as AntsPlatformAPI.AnnotationQueue,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AntsPlatformAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new AntsPlatformAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new AntsPlatformAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new AntsPlatformAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new AntsPlatformAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.AntsPlatformAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.AntsPlatformAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.AntsPlatformAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/annotation-queues/{queueId}.",
        );
      case "unknown":
        throw new errors.AntsPlatformAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get items for a specific annotation queue
   *
   * @param {string} queueId - The unique identifier of the annotation queue
   * @param {AntsPlatformAPI.GetAnnotationQueueItemsRequest} request
   * @param {AnnotationQueues.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AntsPlatformAPI.Error}
   * @throws {@link AntsPlatformAPI.UnauthorizedError}
   * @throws {@link AntsPlatformAPI.AccessDeniedError}
   * @throws {@link AntsPlatformAPI.MethodNotAllowedError}
   * @throws {@link AntsPlatformAPI.NotFoundError}
   *
   * @example
   *     await client.annotationQueues.listQueueItems("queueId")
   */
  public listQueueItems(
    queueId: string,
    request: AntsPlatformAPI.GetAnnotationQueueItemsRequest = {},
    requestOptions?: AnnotationQueues.RequestOptions,
  ): core.HttpResponsePromise<AntsPlatformAPI.PaginatedAnnotationQueueItems> {
    return core.HttpResponsePromise.fromPromise(
      this.__listQueueItems(queueId, request, requestOptions),
    );
  }

  private async __listQueueItems(
    queueId: string,
    request: AntsPlatformAPI.GetAnnotationQueueItemsRequest = {},
    requestOptions?: AnnotationQueues.RequestOptions,
  ): Promise<
    core.WithRawResponse<AntsPlatformAPI.PaginatedAnnotationQueueItems>
  > {
    const { status, page, limit } = request;
    const _queryParams: Record<
      string,
      string | string[] | object | object[] | null
    > = {};
    if (status != null) {
      _queryParams["status"] = status;
    }

    if (page != null) {
      _queryParams["page"] = page.toString();
    }

    if (limit != null) {
      _queryParams["limit"] = limit.toString();
    }

    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/annotation-queues/${encodeURIComponent(queueId)}/items`,
      ),
      method: "GET",
      headers: mergeHeaders(
        this._options?.headers,
        mergeOnlyDefinedHeaders({
          Authorization: await this._getAuthorizationHeader(),
          "X-AntsPlatform-Sdk-Name": requestOptions?.xAntsPlatformSdkName,
          "X-AntsPlatform-Sdk-Version": requestOptions?.xAntsPlatformSdkVersion,
          "X-AntsPlatform-Public-Key": requestOptions?.xAntsPlatformPublicKey,
        }),
        requestOptions?.headers,
      ),
      queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as AntsPlatformAPI.PaginatedAnnotationQueueItems,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AntsPlatformAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new AntsPlatformAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new AntsPlatformAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new AntsPlatformAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new AntsPlatformAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.AntsPlatformAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.AntsPlatformAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.AntsPlatformAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/annotation-queues/{queueId}/items.",
        );
      case "unknown":
        throw new errors.AntsPlatformAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get a specific item from an annotation queue
   *
   * @param {string} queueId - The unique identifier of the annotation queue
   * @param {string} itemId - The unique identifier of the annotation queue item
   * @param {AnnotationQueues.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AntsPlatformAPI.Error}
   * @throws {@link AntsPlatformAPI.UnauthorizedError}
   * @throws {@link AntsPlatformAPI.AccessDeniedError}
   * @throws {@link AntsPlatformAPI.MethodNotAllowedError}
   * @throws {@link AntsPlatformAPI.NotFoundError}
   *
   * @example
   *     await client.annotationQueues.getQueueItem("queueId", "itemId")
   */
  public getQueueItem(
    queueId: string,
    itemId: string,
    requestOptions?: AnnotationQueues.RequestOptions,
  ): core.HttpResponsePromise<AntsPlatformAPI.AnnotationQueueItem> {
    return core.HttpResponsePromise.fromPromise(
      this.__getQueueItem(queueId, itemId, requestOptions),
    );
  }

  private async __getQueueItem(
    queueId: string,
    itemId: string,
    requestOptions?: AnnotationQueues.RequestOptions,
  ): Promise<core.WithRawResponse<AntsPlatformAPI.AnnotationQueueItem>> {
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/annotation-queues/${encodeURIComponent(queueId)}/items/${encodeURIComponent(itemId)}`,
      ),
      method: "GET",
      headers: mergeHeaders(
        this._options?.headers,
        mergeOnlyDefinedHeaders({
          Authorization: await this._getAuthorizationHeader(),
          "X-AntsPlatform-Sdk-Name": requestOptions?.xAntsPlatformSdkName,
          "X-AntsPlatform-Sdk-Version": requestOptions?.xAntsPlatformSdkVersion,
          "X-AntsPlatform-Public-Key": requestOptions?.xAntsPlatformPublicKey,
        }),
        requestOptions?.headers,
      ),
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as AntsPlatformAPI.AnnotationQueueItem,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AntsPlatformAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new AntsPlatformAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new AntsPlatformAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new AntsPlatformAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new AntsPlatformAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.AntsPlatformAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.AntsPlatformAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.AntsPlatformAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/annotation-queues/{queueId}/items/{itemId}.",
        );
      case "unknown":
        throw new errors.AntsPlatformAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Add an item to an annotation queue
   *
   * @param {string} queueId - The unique identifier of the annotation queue
   * @param {AntsPlatformAPI.CreateAnnotationQueueItemRequest} request
   * @param {AnnotationQueues.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AntsPlatformAPI.Error}
   * @throws {@link AntsPlatformAPI.UnauthorizedError}
   * @throws {@link AntsPlatformAPI.AccessDeniedError}
   * @throws {@link AntsPlatformAPI.MethodNotAllowedError}
   * @throws {@link AntsPlatformAPI.NotFoundError}
   *
   * @example
   *     await client.annotationQueues.createQueueItem("queueId", {
   *         objectId: "objectId",
   *         objectType: "TRACE",
   *         status: undefined
   *     })
   */
  public createQueueItem(
    queueId: string,
    request: AntsPlatformAPI.CreateAnnotationQueueItemRequest,
    requestOptions?: AnnotationQueues.RequestOptions,
  ): core.HttpResponsePromise<AntsPlatformAPI.AnnotationQueueItem> {
    return core.HttpResponsePromise.fromPromise(
      this.__createQueueItem(queueId, request, requestOptions),
    );
  }

  private async __createQueueItem(
    queueId: string,
    request: AntsPlatformAPI.CreateAnnotationQueueItemRequest,
    requestOptions?: AnnotationQueues.RequestOptions,
  ): Promise<core.WithRawResponse<AntsPlatformAPI.AnnotationQueueItem>> {
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/annotation-queues/${encodeURIComponent(queueId)}/items`,
      ),
      method: "POST",
      headers: mergeHeaders(
        this._options?.headers,
        mergeOnlyDefinedHeaders({
          Authorization: await this._getAuthorizationHeader(),
          "X-AntsPlatform-Sdk-Name": requestOptions?.xAntsPlatformSdkName,
          "X-AntsPlatform-Sdk-Version": requestOptions?.xAntsPlatformSdkVersion,
          "X-AntsPlatform-Public-Key": requestOptions?.xAntsPlatformPublicKey,
        }),
        requestOptions?.headers,
      ),
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as AntsPlatformAPI.AnnotationQueueItem,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AntsPlatformAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new AntsPlatformAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new AntsPlatformAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new AntsPlatformAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new AntsPlatformAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.AntsPlatformAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.AntsPlatformAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.AntsPlatformAPITimeoutError(
          "Timeout exceeded when calling POST /api/public/annotation-queues/{queueId}/items.",
        );
      case "unknown":
        throw new errors.AntsPlatformAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Update an annotation queue item
   *
   * @param {string} queueId - The unique identifier of the annotation queue
   * @param {string} itemId - The unique identifier of the annotation queue item
   * @param {AntsPlatformAPI.UpdateAnnotationQueueItemRequest} request
   * @param {AnnotationQueues.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AntsPlatformAPI.Error}
   * @throws {@link AntsPlatformAPI.UnauthorizedError}
   * @throws {@link AntsPlatformAPI.AccessDeniedError}
   * @throws {@link AntsPlatformAPI.MethodNotAllowedError}
   * @throws {@link AntsPlatformAPI.NotFoundError}
   *
   * @example
   *     await client.annotationQueues.updateQueueItem("queueId", "itemId", {
   *         status: undefined
   *     })
   */
  public updateQueueItem(
    queueId: string,
    itemId: string,
    request: AntsPlatformAPI.UpdateAnnotationQueueItemRequest,
    requestOptions?: AnnotationQueues.RequestOptions,
  ): core.HttpResponsePromise<AntsPlatformAPI.AnnotationQueueItem> {
    return core.HttpResponsePromise.fromPromise(
      this.__updateQueueItem(queueId, itemId, request, requestOptions),
    );
  }

  private async __updateQueueItem(
    queueId: string,
    itemId: string,
    request: AntsPlatformAPI.UpdateAnnotationQueueItemRequest,
    requestOptions?: AnnotationQueues.RequestOptions,
  ): Promise<core.WithRawResponse<AntsPlatformAPI.AnnotationQueueItem>> {
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/annotation-queues/${encodeURIComponent(queueId)}/items/${encodeURIComponent(itemId)}`,
      ),
      method: "PATCH",
      headers: mergeHeaders(
        this._options?.headers,
        mergeOnlyDefinedHeaders({
          Authorization: await this._getAuthorizationHeader(),
          "X-AntsPlatform-Sdk-Name": requestOptions?.xAntsPlatformSdkName,
          "X-AntsPlatform-Sdk-Version": requestOptions?.xAntsPlatformSdkVersion,
          "X-AntsPlatform-Public-Key": requestOptions?.xAntsPlatformPublicKey,
        }),
        requestOptions?.headers,
      ),
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as AntsPlatformAPI.AnnotationQueueItem,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AntsPlatformAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new AntsPlatformAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new AntsPlatformAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new AntsPlatformAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new AntsPlatformAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.AntsPlatformAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.AntsPlatformAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.AntsPlatformAPITimeoutError(
          "Timeout exceeded when calling PATCH /api/public/annotation-queues/{queueId}/items/{itemId}.",
        );
      case "unknown":
        throw new errors.AntsPlatformAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Remove an item from an annotation queue
   *
   * @param {string} queueId - The unique identifier of the annotation queue
   * @param {string} itemId - The unique identifier of the annotation queue item
   * @param {AnnotationQueues.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AntsPlatformAPI.Error}
   * @throws {@link AntsPlatformAPI.UnauthorizedError}
   * @throws {@link AntsPlatformAPI.AccessDeniedError}
   * @throws {@link AntsPlatformAPI.MethodNotAllowedError}
   * @throws {@link AntsPlatformAPI.NotFoundError}
   *
   * @example
   *     await client.annotationQueues.deleteQueueItem("queueId", "itemId")
   */
  public deleteQueueItem(
    queueId: string,
    itemId: string,
    requestOptions?: AnnotationQueues.RequestOptions,
  ): core.HttpResponsePromise<AntsPlatformAPI.DeleteAnnotationQueueItemResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__deleteQueueItem(queueId, itemId, requestOptions),
    );
  }

  private async __deleteQueueItem(
    queueId: string,
    itemId: string,
    requestOptions?: AnnotationQueues.RequestOptions,
  ): Promise<
    core.WithRawResponse<AntsPlatformAPI.DeleteAnnotationQueueItemResponse>
  > {
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/annotation-queues/${encodeURIComponent(queueId)}/items/${encodeURIComponent(itemId)}`,
      ),
      method: "DELETE",
      headers: mergeHeaders(
        this._options?.headers,
        mergeOnlyDefinedHeaders({
          Authorization: await this._getAuthorizationHeader(),
          "X-AntsPlatform-Sdk-Name": requestOptions?.xAntsPlatformSdkName,
          "X-AntsPlatform-Sdk-Version": requestOptions?.xAntsPlatformSdkVersion,
          "X-AntsPlatform-Public-Key": requestOptions?.xAntsPlatformPublicKey,
        }),
        requestOptions?.headers,
      ),
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as AntsPlatformAPI.DeleteAnnotationQueueItemResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AntsPlatformAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new AntsPlatformAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new AntsPlatformAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new AntsPlatformAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new AntsPlatformAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.AntsPlatformAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.AntsPlatformAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.AntsPlatformAPITimeoutError(
          "Timeout exceeded when calling DELETE /api/public/annotation-queues/{queueId}/items/{itemId}.",
        );
      case "unknown":
        throw new errors.AntsPlatformAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  protected async _getAuthorizationHeader(): Promise<string | undefined> {
    const username = await core.Supplier.get(this._options.username);
    const password = await core.Supplier.get(this._options.password);
    if (username != null && password != null) {
      return core.BasicAuth.toAuthorizationHeader({
        username: username,
        password: password,
      });
    }

    return undefined;
  }
}
