/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface CreateGenerationBody extends AntsPlatformAPI.CreateSpanBody {
  completionStartTime?: string;
  model?: string;
  modelParameters?: Record<string, AntsPlatformAPI.MapValue>;
  usage?: AntsPlatformAPI.IngestionUsage;
  usageDetails?: AntsPlatformAPI.UsageDetails;
  costDetails?: Record<string, number>;
  promptName?: string;
  promptVersion?: number;
}
