/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export type IngestionUsage =
  | AntsPlatformAPI.Usage
  | AntsPlatformAPI.OpenAiUsage;
