/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export type IngestionEvent =
  /**
   * Creates a new trace. Upserts on id for updates if trace with id exists. */
  | AntsPlatformAPI.IngestionEvent.TraceCreate
  /**
   * Creates a new score. Upserts on id for updates if score with id exists. */
  | AntsPlatformAPI.IngestionEvent.ScoreCreate
  /**
   * Creates a new span. */
  | AntsPlatformAPI.IngestionEvent.SpanCreate
  /**
   * Updates span based on id. */
  | AntsPlatformAPI.IngestionEvent.SpanUpdate
  /**
   * Creates a new generation. */
  | AntsPlatformAPI.IngestionEvent.GenerationCreate
  /**
   * Updates a generation based on id. */
  | AntsPlatformAPI.IngestionEvent.GenerationUpdate
  /**
   * Creates an event. */
  | AntsPlatformAPI.IngestionEvent.EventCreate
  /**
   * AntsPlatform SDKs only, used for debugging purposes. */
  | AntsPlatformAPI.IngestionEvent.SdkLog
  /**
   * Deprecated event type */
  | AntsPlatformAPI.IngestionEvent.ObservationCreate
  /**
   * Deprecated event type */
  | AntsPlatformAPI.IngestionEvent.ObservationUpdate;

export namespace IngestionEvent {
  export interface TraceCreate extends AntsPlatformAPI.TraceEvent {
    type: "trace-create";
  }

  export interface ScoreCreate extends AntsPlatformAPI.ScoreEvent {
    type: "score-create";
  }

  export interface SpanCreate extends AntsPlatformAPI.CreateSpanEvent {
    type: "span-create";
  }

  export interface SpanUpdate extends AntsPlatformAPI.UpdateSpanEvent {
    type: "span-update";
  }

  export interface GenerationCreate
    extends AntsPlatformAPI.CreateGenerationEvent {
    type: "generation-create";
  }

  export interface GenerationUpdate
    extends AntsPlatformAPI.UpdateGenerationEvent {
    type: "generation-update";
  }

  export interface EventCreate extends AntsPlatformAPI.CreateEventEvent {
    type: "event-create";
  }

  export interface SdkLog extends AntsPlatformAPI.SdkLogEvent {
    type: "sdk-log";
  }

  export interface ObservationCreate
    extends AntsPlatformAPI.CreateObservationEvent {
    type: "observation-create";
  }

  export interface ObservationUpdate
    extends AntsPlatformAPI.UpdateObservationEvent {
    type: "observation-update";
  }
}
