/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface ObservationBody {
  id?: string;
  traceId?: string;
  type: AntsPlatformAPI.ObservationType;
  name?: string;
  startTime?: string;
  endTime?: string;
  completionStartTime?: string;
  model?: string;
  modelParameters?: Record<string, AntsPlatformAPI.MapValue>;
  input?: unknown;
  version?: string;
  metadata?: unknown;
  output?: unknown;
  usage?: AntsPlatformAPI.Usage;
  level?: AntsPlatformAPI.ObservationLevel;
  statusMessage?: string;
  parentObservationId?: string;
  environment?: string;
}
