/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface OptionalObservationBody {
  traceId?: string;
  name?: string;
  startTime?: string;
  metadata?: unknown;
  input?: unknown;
  output?: unknown;
  level?: AntsPlatformAPI.ObservationLevel;
  statusMessage?: string;
  parentObservationId?: string;
  version?: string;
  environment?: string;
}
