/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface ScoreEvent extends AntsPlatformAPI.BaseEvent {
  body: AntsPlatformAPI.ScoreBody;
}
