/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface GetCommentsResponse {
  data: AntsPlatformAPI.Comment[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
