/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface PaginatedDatasetItems {
  data: AntsPlatformAPI.DatasetItem[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
