/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface Observations {
  data: AntsPlatformAPI.Observation[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
