/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AntsPlatformAPI from "../../../index.js";

export interface ObservationsViews {
  data: AntsPlatformAPI.ObservationsView[];
  meta: AntsPlatformAPI.utils.MetaResponse;
}
